//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTPatcher.SpriteEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTPatcher.SpriteEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARUTE_SEQ {
            get {
                object obj = ResourceManager.GetObject("ARUTE_SEQ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ARUTE_SHP {
            get {
                object obj = ResourceManager.GetObject("ARUTE_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CYOKO_SEQ {
            get {
                object obj = ResourceManager.GetObject("CYOKO_SEQ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CYOKO_SHP {
            get {
                object obj = ResourceManager.GetObject("CYOKO_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EFF1_SHP {
            get {
                object obj = ResourceManager.GetObject("EFF1_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] EFF2_SHP {
            get {
                object obj = ResourceManager.GetObject("EFF2_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KANZEN_SEQ {
            get {
                object obj = ResourceManager.GetObject("KANZEN_SEQ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] KANZEN_SHP {
            get {
                object obj = ResourceManager.GetObject("KANZEN_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MON_SEQ {
            get {
                object obj = ResourceManager.GetObject("MON_SEQ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MON_SHP {
            get {
                object obj = ResourceManager.GetObject("MON_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PatchedDummyFolder {
            get {
                object obj = ResourceManager.GetObject("PatchedDummyFolder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PspFiles&gt;
        ///    &lt;Section Filename=&quot;FRAME.BIN&quot; Filesize=&quot;37568&quot;&gt;
        ///        &lt;PalettedImage4bpp&gt;
        ///            &lt;Name&gt;FRAME.BIN&lt;/Name&gt;
        ///            &lt;Width&gt;256&lt;/Width&gt;
        ///            &lt;Height&gt;288&lt;/Height&gt;
        ///            &lt;FFTPack&gt;EVENT_FRAME_BIN&lt;/FFTPack&gt;
        ///            &lt;PaletteCount&gt;22&lt;/PaletteCount&gt;
        ///            &lt;DefaultPalette&gt;5&lt;/DefaultPalette&gt;
        ///            &lt;PalettePosition&gt;
        ///                &lt;Offset&gt;36864&lt;/Offset&gt;
        ///                &lt;Length&gt;32&lt;/Length&gt;
        ///            &lt;/PalettePosit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PSPFiles {
            get {
                return ResourceManager.GetString("PSPFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PsxFiles&gt;
        ///    &lt;Section Filename=&quot;FRAME.BIN&quot; Filesize=&quot;37568&quot;&gt;
        ///        &lt;PalettedImage4bpp&gt;
        ///            &lt;Name&gt;FRAME.BIN&lt;/Name&gt;
        ///            &lt;Width&gt;256&lt;/Width&gt;
        ///            &lt;Height&gt;288&lt;/Height&gt;
        ///            &lt;Sector&gt;EVENT_FRAME_BIN&lt;/Sector&gt;
        ///            &lt;PaletteCount&gt;22&lt;/PaletteCount&gt;
        ///            &lt;DefaultPalette&gt;5&lt;/DefaultPalette&gt;
        ///            &lt;PalettePosition&gt;
        ///                &lt;Offset&gt;36864&lt;/Offset&gt;
        ///                &lt;Length&gt;32&lt;/Length&gt;
        ///            &lt;/PalettePositio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PSXFiles {
            get {
                return ResourceManager.GetString("PSXFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RUKA_SEQ {
            get {
                object obj = ResourceManager.GetObject("RUKA_SEQ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon sprite {
            get {
                object obj = ResourceManager.GetObject("sprite", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TYPE1_SEQ {
            get {
                object obj = ResourceManager.GetObject("TYPE1_SEQ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TYPE1_SHP {
            get {
                object obj = ResourceManager.GetObject("TYPE1_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TYPE2_SEQ {
            get {
                object obj = ResourceManager.GetObject("TYPE2_SEQ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TYPE2_SHP {
            get {
                object obj = ResourceManager.GetObject("TYPE2_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WEP1_SEQ {
            get {
                object obj = ResourceManager.GetObject("WEP1_SEQ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WEP1_SHP {
            get {
                object obj = ResourceManager.GetObject("WEP1_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WEP2_SEQ {
            get {
                object obj = ResourceManager.GetObject("WEP2_SEQ", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WEP2_SHP {
            get {
                object obj = ResourceManager.GetObject("WEP2_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
